language: java
branches:
  only:
    - develop
    - master
notifications:
  email:
    recipients:
      - andres.grisalesg@udea.edu.co
      - angel.naranjo@udea.edu.co

script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
#SONARCLOUD
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mjajudea -Dsonar.login=$SONAR